from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import networkx as nx
import scipy.sparse as sp


VOTES_PATH = Path("data/processed/rfa_votes_clean.csv")
OUTPUT_DIR = Path("outputs")
FIGURE_DIR = Path("figures")

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
FIGURE_DIR.mkdir(parents=True, exist_ok=True)


ALPHA = 0.85
MAX_ITER = 200
TOL = 1e-12


def zscore(series: pd.Series) -> pd.Series:
    """
    Standardize a pandas Series.

    If the standard deviation is zero, return zeros to avoid division by zero.
    """
    std = series.std(ddof=0)
    if std == 0 or pd.isna(std):
        return pd.Series(np.zeros(len(series)), index=series.index)
    return (series - series.mean()) / std


def build_weighted_graph(votes: pd.DataFrame, vote_value: int, all_nodes: list[str]) -> nx.DiGraph:
    """
    Build a weighted directed graph for one vote layer.

    vote_value:
        1  = support graph
        0  = neutral graph
        -1 = oppose graph
    """
    layer = votes[votes["vote"] == vote_value].copy()

    edge_counts = (
        layer
        .groupby(["source", "target"], as_index=False)
        .size()
        .rename(columns={"size": "weight"})
    )

    G = nx.DiGraph()
    G.add_nodes_from(all_nodes)

    for row in edge_counts.itertuples(index=False):
        G.add_edge(row.source, row.target, weight=float(row.weight))

    return G


def compute_layer_pagerank(votes: pd.DataFrame, vote_value: int, all_nodes: list[str]) -> dict:
    """
    Compute ordinary weighted PageRank for one vote layer.
    """
    G = build_weighted_graph(votes, vote_value, all_nodes)

    # NetworkX PageRank handles dangling nodes and uses a stochastic formulation.
    return nx.pagerank(G, alpha=ALPHA, weight="weight")


def build_lifted_signed_transition(votes: pd.DataFrame, node_to_idx: dict[str, int]) -> tuple[sp.csr_matrix, np.ndarray]:
    """
    Build the lifted signed transition matrix for support and oppose votes.

    Each original node i has two lifted states:

        i         = positive state
        i + n     = negative state

    Support edges preserve sign:
        (i,+) -> (j,+)
        (i,-) -> (j,-)

    Oppose edges flip sign:
        (i,+) -> (j,-)
        (i,-) -> (j,+)

    The returned matrix L is row-substochastic: non-dangling rows sum to 1,
    dangling rows sum to 0. Dangling mass is handled during PageRank iteration.
    """
    signed = votes[votes["vote"].isin([1, -1])].copy()

    edge_counts = (
        signed
        .groupby(["source", "target", "vote"], as_index=False)
        .size()
        .rename(columns={"size": "weight"})
    )

    n = len(node_to_idx)

    # Total signed out-weight by source node, using support and oppose only.
    out_weight = np.zeros(n, dtype=float)

    for row in edge_counts.itertuples(index=False):
        source_idx = node_to_idx[row.source]
        out_weight[source_idx] += float(row.weight)

    rows = []
    cols = []
    data = []

    for row in edge_counts.itertuples(index=False):
        source_idx = node_to_idx[row.source]
        target_idx = node_to_idx[row.target]

        denom = out_weight[source_idx]
        if denom == 0:
            continue

        prob = float(row.weight) / denom

        if int(row.vote) == 1:
            # Support preserves sign.
            # Positive state -> positive state
            rows.append(source_idx)
            cols.append(target_idx)
            data.append(prob)

            # Negative state -> negative state
            rows.append(source_idx + n)
            cols.append(target_idx + n)
            data.append(prob)

        elif int(row.vote) == -1:
            # Oppose flips sign.
            # Positive state -> negative state
            rows.append(source_idx)
            cols.append(target_idx + n)
            data.append(prob)

            # Negative state -> positive state
            rows.append(source_idx + n)
            cols.append(target_idx)
            data.append(prob)

    L = sp.csr_matrix((data, (rows, cols)), shape=(2 * n, 2 * n))

    # Dangling rows correspond to original nodes with no outgoing signed edges.
    dangling_original = out_weight == 0
    dangling_lifted = np.concatenate([dangling_original, dangling_original])

    return L, dangling_lifted


def signed_pagerank(votes: pd.DataFrame, all_nodes: list[str]) -> pd.DataFrame:
    """
    Compute lifted-state signed PageRank.

    Teleportation is placed uniformly over the positive layer. This means the
    random surfer restarts as positive/neutral reputation mass, and negative
    reputation mass is generated by traversing oppose edges.
    """
    n = len(all_nodes)
    node_to_idx = {node: idx for idx, node in enumerate(all_nodes)}

    L, dangling = build_lifted_signed_transition(votes, node_to_idx)

    # Teleport uniformly into positive states only.
    teleport = np.zeros(2 * n, dtype=float)
    teleport[:n] = 1.0 / n

    rho = teleport.copy()

    for iteration in range(MAX_ITER):
        dangling_mass = rho[dangling].sum()

        new_rho = ALPHA * (L.T @ rho + dangling_mass * teleport) + (1.0 - ALPHA) * teleport

        # Normalize defensively to avoid numerical drift.
        new_rho = new_rho / new_rho.sum()

        diff = np.abs(new_rho - rho).sum()

        rho = new_rho

        if diff < TOL:
            print(f"Signed PageRank converged in {iteration + 1} iterations.")
            break
    else:
        print(f"Signed PageRank reached max iterations ({MAX_ITER}) with final L1 diff={diff:.3e}.")

    positive = rho[:n]
    negative = rho[n:]

    scores = pd.DataFrame({
        "node": all_nodes,
        "signed_positive": positive,
        "signed_negative": negative,
    })

    scores["signed_attention"] = scores["signed_positive"] + scores["signed_negative"]
    scores["signed_net"] = scores["signed_positive"] - scores["signed_negative"]

    scores["signed_balance"] = np.where(
        scores["signed_attention"] > 0,
        scores["signed_net"] / scores["signed_attention"],
        0.0
    )

    return scores


def add_layer_scores(votes: pd.DataFrame, scores: pd.DataFrame, all_nodes: list[str]) -> pd.DataFrame:
    """
    Add ordinary PageRank scores for support, oppose, and neutral layers.
    """
    print("Computing support PageRank...")
    pr_support = compute_layer_pagerank(votes, 1, all_nodes)

    print("Computing oppose PageRank...")
    pr_oppose = compute_layer_pagerank(votes, -1, all_nodes)

    print("Computing neutral PageRank...")
    pr_neutral = compute_layer_pagerank(votes, 0, all_nodes)

    scores["pagerank_support"] = scores["node"].map(pr_support)
    scores["pagerank_oppose"] = scores["node"].map(pr_oppose)
    scores["pagerank_neutral"] = scores["node"].map(pr_neutral)

    # Descriptive composite scores.
    scores["support_z"] = zscore(scores["pagerank_support"])
    scores["oppose_z"] = zscore(scores["pagerank_oppose"])
    scores["neutral_z"] = zscore(scores["pagerank_neutral"])

    scores["net_support_minus_oppose_z"] = scores["support_z"] - scores["oppose_z"]
    scores["controversy_z"] = scores["support_z"] + scores["oppose_z"]

    return scores


def add_rank_columns(scores: pd.DataFrame) -> pd.DataFrame:
    """
    Add rank and rank-shift diagnostics.
    """
    scores["support_rank"] = (
        scores["pagerank_support"]
        .rank(method="min", ascending=False)
        .astype(int)
    )

    scores["signed_net_rank"] = (
        scores["signed_net"]
        .rank(method="min", ascending=False)
        .astype(int)
    )

    scores["signed_attention_rank"] = (
        scores["signed_attention"]
        .rank(method="min", ascending=False)
        .astype(int)
    )

    # Positive value means the node ranks lower after signed PageRank.
    # Negative value means the node rises after signed PageRank.
    scores["rank_shift_signed_minus_support"] = scores["signed_net_rank"] - scores["support_rank"]
    scores["rank_shift_abs"] = scores["rank_shift_signed_minus_support"].abs()

    return scores


def save_top_nodes(scores: pd.DataFrame) -> None:
    """
    Save a compact top-node table across multiple signed/neutral centrality views.
    """
    categories = [
        ("top_support_pagerank", "pagerank_support", False),
        ("top_oppose_pagerank", "pagerank_oppose", False),
        ("top_neutral_pagerank", "pagerank_neutral", False),
        ("top_signed_positive", "signed_positive", False),
        ("top_signed_negative", "signed_negative", False),
        ("top_signed_net", "signed_net", False),
        ("top_signed_attention", "signed_attention", False),
        ("top_controversy_z", "controversy_z", False),
        ("largest_absolute_rank_shift", "rank_shift_abs", False),
    ]

    frames = []

    for category, score_col, ascending in categories:
        subset = (
            scores
            .sort_values(score_col, ascending=ascending)
            .head(25)
            .copy()
        )

        subset.insert(0, "category", category)
        subset.insert(1, "category_rank", range(1, len(subset) + 1))
        subset["score_column"] = score_col
        subset["score_value"] = subset[score_col]

        frames.append(
            subset[[
                "category",
                "category_rank",
                "node",
                "score_column",
                "score_value",
                "pagerank_support",
                "pagerank_oppose",
                "pagerank_neutral",
                "signed_positive",
                "signed_negative",
                "signed_net",
                "signed_attention",
                "signed_balance",
                "support_rank",
                "signed_net_rank",
                "rank_shift_signed_minus_support",
            ]]
        )

    top_nodes = pd.concat(frames, ignore_index=True)
    top_nodes.to_csv(OUTPUT_DIR / "signed_pagerank_top_nodes.csv", index=False)


def save_correlations(scores: pd.DataFrame) -> None:
    """
    Save Pearson and Spearman correlations among signed and layer centrality scores.
    """
    score_cols = [
        "pagerank_support",
        "pagerank_oppose",
        "pagerank_neutral",
        "signed_positive",
        "signed_negative",
        "signed_net",
        "signed_attention",
        "signed_balance",
        "net_support_minus_oppose_z",
        "controversy_z",
    ]

    rows = []

    for method in ["pearson", "spearman"]:
        corr = scores[score_cols].corr(method=method)

        for i, col_i in enumerate(score_cols):
            for col_j in score_cols[i + 1:]:
                rows.append({
                    "method": method,
                    "score_x": col_i,
                    "score_y": col_j,
                    "correlation": corr.loc[col_i, col_j],
                })

    corr_df = pd.DataFrame(rows)
    corr_df.to_csv(OUTPUT_DIR / "signed_score_correlations.csv", index=False)


def make_figures(scores: pd.DataFrame) -> None:
    """
    Generate requested signed PageRank extension figures.
    """

    # 1. Support PageRank vs Oppose PageRank
    plt.figure(figsize=(7, 5))
    plt.scatter(
        scores["pagerank_support"],
        scores["pagerank_oppose"],
        s=8,
        alpha=0.35
    )
    plt.xscale("log")
    plt.yscale("log")
    plt.xlabel("Support PageRank")
    plt.ylabel("Oppose PageRank")
    plt.title("Support PageRank vs Oppose PageRank")
    plt.tight_layout()
    plt.savefig(FIGURE_DIR / "signed_support_vs_oppose.png", dpi=200)
    plt.close()

    # 2. Signed net score distribution
    plt.figure(figsize=(7, 5))
    plt.hist(scores["signed_net"], bins=50)
    plt.xlabel("Signed Net Score: positive mass minus negative mass")
    plt.ylabel("Number of users")
    plt.title("Distribution of Lifted Signed PageRank Net Scores")
    plt.tight_layout()
    plt.savefig(FIGURE_DIR / "signed_net_score_distribution.png", dpi=200)
    plt.close()

    # 3. Largest rank shifts between support-only PageRank and signed net rank
    top_shift = (
        scores
        .sort_values("rank_shift_abs", ascending=False)
        .head(20)
        .sort_values("rank_shift_signed_minus_support")
        .copy()
    )

    plt.figure(figsize=(10, 8))
    plt.barh(top_shift["node"], top_shift["rank_shift_signed_minus_support"])
    plt.xlabel("Signed net rank minus support-only rank")
    plt.ylabel("User")
    plt.title("Top 20 Absolute Rank Shifts After Signed PageRank")
    plt.tight_layout()
    plt.savefig(FIGURE_DIR / "signed_rank_shift_top20.png", dpi=200)
    plt.close()

    # 4. Neutral PageRank vs Support PageRank
    plt.figure(figsize=(7, 5))
    plt.scatter(
        scores["pagerank_support"],
        scores["pagerank_neutral"],
        s=8,
        alpha=0.35
    )
    plt.xscale("log")
    plt.yscale("log")
    plt.xlabel("Support PageRank")
    plt.ylabel("Neutral PageRank")
    plt.title("Neutral Attention PageRank vs Support PageRank")
    plt.tight_layout()
    plt.savefig(FIGURE_DIR / "neutral_vs_support_pagerank.png", dpi=200)
    plt.close()


def main():
    if not VOTES_PATH.exists():
        raise FileNotFoundError(
            f"Could not find {VOTES_PATH}. Run src/02_clean_data.py first."
        )

    print(f"Reading cleaned votes from: {VOTES_PATH}")

    votes = pd.read_csv(VOTES_PATH, keep_default_na=False)

    votes["vote"] = pd.to_numeric(votes["vote"], errors="coerce")
    votes = votes.dropna(subset=["vote"]).copy()
    votes["vote"] = votes["vote"].astype(int)

    votes["source"] = votes["source"].astype(str).str.strip()
    votes["target"] = votes["target"].astype(str).str.strip()

    votes = votes[(votes["source"] != "") & (votes["target"] != "")].copy()
    votes = votes[votes["source"] != votes["target"]].copy()

    all_nodes = sorted(set(votes["source"]).union(set(votes["target"])))

    print(f"Total nodes across all vote layers: {len(all_nodes):,}")
    print("Computing lifted signed PageRank from support and oppose votes...")

    scores = signed_pagerank(votes, all_nodes)
    scores = add_layer_scores(votes, scores, all_nodes)
    scores = add_rank_columns(scores)

    # Put frequently used columns first.
    first_cols = [
        "node",
        "pagerank_support",
        "pagerank_oppose",
        "pagerank_neutral",
        "signed_positive",
        "signed_negative",
        "signed_attention",
        "signed_net",
        "signed_balance",
        "support_rank",
        "signed_net_rank",
        "rank_shift_signed_minus_support",
        "rank_shift_abs",
        "net_support_minus_oppose_z",
        "controversy_z",
    ]

    remaining_cols = [c for c in scores.columns if c not in first_cols]
    scores = scores[first_cols + remaining_cols]

    scores.to_csv(OUTPUT_DIR / "signed_pagerank_scores.csv", index=False)

    save_top_nodes(scores)
    save_correlations(scores)
    make_figures(scores)

    print("Signed PageRank extension complete.")
    print(f"Saved scores to: {OUTPUT_DIR / 'signed_pagerank_scores.csv'}")
    print(f"Saved top-node table to: {OUTPUT_DIR / 'signed_pagerank_top_nodes.csv'}")
    print(f"Saved correlations to: {OUTPUT_DIR / 'signed_score_correlations.csv'}")
    print("Saved signed PageRank figures to figures/.")

    print("\nTop 10 signed net nodes:")
    print(
        scores
        .sort_values("signed_net", ascending=False)
        [["node", "signed_net", "signed_positive", "signed_negative", "pagerank_support", "pagerank_oppose"]]
        .head(10)
    )


if __name__ == "__main__":
    main()